# Generated by Django 2.2.1 on 2020-11-03 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_attend_time', models.DateTimeField(verbose_name='出勤予定時刻')),
                ('scheduled_leave_time', models.DateTimeField(verbose_name='退勤予定時刻')),
                ('attend_time', models.DateTimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('leave_time', models.DateTimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('work_time', models.DurationField(default=datetime.timedelta(0), verbose_name='労働時間')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考欄')),
            ],
        ),
    ]
