# Generated by Django 2.2.1 on 2020-11-01 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出勤時刻'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退勤時刻'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scheduled_attend_time',
            field=models.DateTimeField(verbose_name='出勤予定時刻'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scheduled_leave_time',
            field=models.DateTimeField(verbose_name='退勤予定時刻'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ名'),
        ),
    ]
