# Generated by Django 2.2.1 on 2020-11-02 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201102_1324'),
        ('attendance2', '0002_auto_20201101_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company', verbose_name='会社名'),
            preserve_default=False,
        ),
    ]
