# Generated by Django 2.2.1 on 2020-11-02 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0004_auto_20201102_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attendance_company_name', to=settings.AUTH_USER_MODEL, verbose_name='会社名'),
        ),
    ]
