# Generated by Django 2.2.1 on 2020-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0005_auto_20201102_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='会社名'),
        ),
    ]
