# Generated by Django 2.2.1 on 2020-11-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance2', '0006_auto_20201102_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='company_name',
        ),
    ]
