# Generated by Django 2.2.1 on 2020-10-13 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201013_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='authority',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
