# Generated by Django 2.2.1 on 2020-11-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201013_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_password1', models.CharField(max_length=100)),
                ('company_password2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='authority',
            field=models.CharField(choices=[('管理者', '管理者'), ('一般人', '一般人')], max_length=100, verbose_name='カラム名'),
        ),
    ]
