# Generated by Django 2.2.1 on 2020-11-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201102_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_password1',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
